@startuml
'https://plantuml.com/class-diagram

class Student {
    - name: String
    - grade : GRADE
    - group : int
    - secretNickname : String
    + Student(name: String, grade: GRADE, group : int) : void
    + getGrade() : GRADE
    + getName(): String
    + increaseGrade(): void
    + decreaseGrade(): void
}

Student "1" -- "1" GRADE : has

enum GRADE {
A
B
C
D
E
F
}

@enduml