@startuml
'https://plantuml.com/class-diagram

class Student {
    - name: String
    - grade : Grade
    - group : int
    - secretNickname : String
    + Student(name: String, grade: Grade, group : int) : void
    + getGrade() : Grade
    + getName(): String
    + increaseGrade(): void
    + decreaseGrade(): void
}

Student "1" -- "1" Grade : has

enum Grade {
A
B
C
D
E
F
}

@enduml